import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { format, subDays } from "date-fns";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { supabase } from "@/integrations/supabase/fixed-client";
import { 
  TrendingUp, 
  Users, 
  DollarSign, 
  BarChart3, 
  Building2, 
  Activity,
  ArrowUpRight,
  ArrowDownRight,
  Plus,
  CalendarIcon
} from "lucide-react";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Area,
  AreaChart
} from "recharts";

interface DashboardStats {
  totalClients: number;
  activeClients: number;
  totalRevenue: number;
  totalSpend: number;
  avgROI: number;
  totalDonations: number;
  revenueChange: number;
  clientChange: number;
}

interface ChartDataPoint {
  date: string;
  revenue: number;
  spend: number;
  roi: number;
  donations: number;
}

interface CampaignPerformance {
  name: string;
  revenue: number;
  spend: number;
  roi: number;
}

const COLORS = ['#667eea', '#764ba2', '#f093fb', '#4facfe', '#43e97b'];

type DateRangePreset = '7' | '30' | '90' | 'custom';

interface DateRange {
  from: Date;
  to: Date;
}

export function DashboardHome() {
  const navigate = useNavigate();
  const [stats, setStats] = useState<DashboardStats>({
    totalClients: 0,
    activeClients: 0,
    totalRevenue: 0,
    totalSpend: 0,
    avgROI: 0,
    totalDonations: 0,
    revenueChange: 0,
    clientChange: 0,
  });
  const [chartData, setChartData] = useState<ChartDataPoint[]>([]);
  const [campaignData, setCampaignData] = useState<CampaignPerformance[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [dateRangePreset, setDateRangePreset] = useState<DateRangePreset>('30');
  const [customDateRange, setCustomDateRange] = useState<DateRange>({
    from: subDays(new Date(), 30),
    to: new Date(),
  });

  useEffect(() => {
    fetchDashboardStats();
  }, []);

  useEffect(() => {
    fetchChartData();
    fetchCampaignPerformance();
  }, [dateRangePreset, customDateRange]);

  const fetchDashboardStats = async () => {
    try {
      // Using any to bypass type issues with autogenerated types
      const orgsQuery = (supabase as any).from('client_organizations').select('id, is_active');
      const metricsQuery = (supabase as any).from('daily_aggregated_metrics').select('total_funds_raised, total_ad_spend, total_sms_cost, roi_percentage, total_donations');
      
      const [orgsResult, metricsResult] = await Promise.all([orgsQuery, metricsQuery]);
      
      const organizations = orgsResult.data || [];
      const metrics = metricsResult.data || [];

      // Calculate totals
      const totalRevenue = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_funds_raised) || 0), 0);
      const totalAdSpend = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_ad_spend) || 0), 0);
      const totalSmsSpend = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_sms_cost) || 0), 0);
      const totalSpend = totalAdSpend + totalSmsSpend;
      const totalDonations = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_donations) || 0), 0);
      const avgROI = totalSpend > 0 ? ((totalRevenue - totalSpend) / totalSpend) * 100 : 0;

      setStats({
        totalClients: organizations.length,
        activeClients: organizations.filter((o: any) => o.is_active).length,
        totalRevenue,
        totalSpend,
        avgROI,
        totalDonations,
        revenueChange: 12.5,
        clientChange: 8.2,
      });
    } catch (error) {
      console.error('Error fetching dashboard stats:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const getDateRange = (): DateRange => {
    const today = new Date();
    if (dateRangePreset === 'custom') {
      return customDateRange;
    }
    const daysAgo = parseInt(dateRangePreset);
    return {
      from: subDays(today, daysAgo),
      to: today,
    };
  };

  const fetchChartData = async () => {
    try {
      const dateRange = getDateRange();
      const fromDate = format(dateRange.from, 'yyyy-MM-dd');
      const toDate = format(dateRange.to, 'yyyy-MM-dd');

      const { data: metrics } = await (supabase as any)
        .from('daily_aggregated_metrics')
        .select('date, total_funds_raised, total_ad_spend, total_sms_cost, roi_percentage, total_donations')
        .gte('date', fromDate)
        .lte('date', toDate)
        .order('date', { ascending: true });

      if (metrics) {
        const formattedData: ChartDataPoint[] = metrics.map((m: any) => ({
          date: new Date(m.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
          revenue: Number(m.total_funds_raised) || 0,
          spend: Number(m.total_ad_spend) + Number(m.total_sms_cost) || 0,
          roi: Number(m.roi_percentage) || 0,
          donations: Number(m.total_donations) || 0,
        }));
        setChartData(formattedData);
      }
    } catch (error) {
      console.error('Error fetching chart data:', error);
    }
  };

  const fetchCampaignPerformance = async () => {
    try {
      const dateRange = getDateRange();
      const fromDate = format(dateRange.from, 'yyyy-MM-dd');
      const toDate = format(dateRange.to, 'yyyy-MM-dd');

      // Fetch top campaigns by revenue
      const { data: campaigns } = await (supabase as any)
        .from('meta_campaigns')
        .select('campaign_name, campaign_id')
        .eq('status', 'ACTIVE')
        .limit(5);

      if (campaigns) {
        const performanceData: CampaignPerformance[] = await Promise.all(
          campaigns.map(async (campaign: any) => {
            const { data: metrics } = await (supabase as any)
              .from('meta_ad_metrics')
              .select('spend, conversions, conversion_value')
              .eq('campaign_id', campaign.campaign_id)
              .gte('date', fromDate)
              .lte('date', toDate);

            const totalSpend = metrics?.reduce((sum: number, m: any) => sum + Number(m.spend || 0), 0) || 0;
            const totalRevenue = metrics?.reduce((sum: number, m: any) => sum + Number(m.conversion_value || 0), 0) || 0;
            const roi = totalSpend > 0 ? ((totalRevenue - totalSpend) / totalSpend) * 100 : 0;

            return {
              name: campaign.campaign_name || 'Unknown Campaign',
              revenue: totalRevenue,
              spend: totalSpend,
              roi: roi,
            };
          })
        );

        setCampaignData(performanceData.sort((a, b) => b.revenue - a.revenue));
      }
    } catch (error) {
      console.error('Error fetching campaign performance:', error);
    }
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const formatNumber = (value: number) => {
    return new Intl.NumberFormat('en-US').format(value);
  };

  const handleDateRangeChange = (value: DateRangePreset) => {
    setDateRangePreset(value);
  };

  const handleCustomDateChange = (type: 'from' | 'to', date: Date | undefined) => {
    if (!date) return;
    setCustomDateRange(prev => ({
      ...prev,
      [type]: date,
    }));
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-lg text-muted-foreground">Loading dashboard...</div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Welcome Section with Date Filter */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Dashboard Overview</h2>
          <p className="text-muted-foreground mt-2">
            Monitor your organization's performance and key metrics
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Select value={dateRangePreset} onValueChange={handleDateRangeChange}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Select range" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="7">Last 7 days</SelectItem>
              <SelectItem value="30">Last 30 days</SelectItem>
              <SelectItem value="90">Last 90 days</SelectItem>
              <SelectItem value="custom">Custom range</SelectItem>
            </SelectContent>
          </Select>
          
          {dateRangePreset === 'custom' && (
            <div className="flex items-center gap-2">
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-[140px] justify-start text-left font-normal">
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {format(customDateRange.from, 'MMM dd, yyyy')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={customDateRange.from}
                    onSelect={(date) => handleCustomDateChange('from', date)}
                    initialFocus
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
              
              <span className="text-muted-foreground">to</span>
              
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-[140px] justify-start text-left font-normal">
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {format(customDateRange.to, 'MMM dd, yyyy')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={customDateRange.to}
                    onSelect={(date) => handleCustomDateChange('to', date)}
                    initialFocus
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
          )}
          
          <Button onClick={() => navigate('/admin/client-view/a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d')} variant="outline">
            <Plus className="h-4 w-4 mr-2" />
            View Demo
          </Button>
        </div>
      </div>

      {/* Key Metrics Grid */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <Card className="hover:shadow-lg transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
            <DollarSign className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatCurrency(stats.totalRevenue)}</div>
            <p className="text-xs text-muted-foreground flex items-center mt-1">
              {stats.revenueChange > 0 ? (
                <>
                  <ArrowUpRight className="h-3 w-3 text-green-500 mr-1" />
                  <span className="text-green-500">+{stats.revenueChange}%</span>
                </>
              ) : (
                <>
                  <ArrowDownRight className="h-3 w-3 text-red-500 mr-1" />
                  <span className="text-red-500">{stats.revenueChange}%</span>
                </>
              )}
              <span className="ml-1">from last month</span>
            </p>
          </CardContent>
        </Card>

        <Card className="hover:shadow-lg transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Clients</CardTitle>
            <Building2 className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.activeClients}</div>
            <p className="text-xs text-muted-foreground flex items-center mt-1">
              <span className="text-muted-foreground">of {stats.totalClients} total</span>
              {stats.clientChange > 0 && (
                <>
                  <ArrowUpRight className="h-3 w-3 text-green-500 ml-2 mr-1" />
                  <span className="text-green-500">+{stats.clientChange}%</span>
                </>
              )}
            </p>
          </CardContent>
        </Card>

        <Card className="hover:shadow-lg transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Average ROI</CardTitle>
            <TrendingUp className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.avgROI.toFixed(1)}%</div>
            <p className="text-xs text-muted-foreground mt-1">
              Return on investment
            </p>
          </CardContent>
        </Card>

        <Card className="hover:shadow-lg transition-shadow">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Donations</CardTitle>
            <Activity className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatNumber(stats.totalDonations)}</div>
            <p className="text-xs text-muted-foreground mt-1">
              Across all campaigns
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Demo Organization Card */}
      <Card className="bg-gradient-to-br from-primary/10 to-primary/5 border-primary/20">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center gap-2">
            🎯 Demo Organization
          </CardTitle>
          <CardDescription>
            Explore sample data with the Progressive Victory Fund organization
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 bg-background rounded-lg border">
              <div className="text-sm text-muted-foreground">Total Funds Raised</div>
              <div className="text-2xl font-bold text-primary">$245,750</div>
            </div>
            <div className="p-4 bg-background rounded-lg border">
              <div className="text-sm text-muted-foreground">Ad Spend</div>
              <div className="text-2xl font-bold text-primary">$18,500</div>
            </div>
            <div className="p-4 bg-background rounded-lg border">
              <div className="text-sm text-muted-foreground">ROI</div>
              <div className="text-2xl font-bold text-primary">1,228%</div>
            </div>
          </div>
          <Button 
            onClick={() => navigate('/admin/client-view/a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d')}
            className="w-full"
          >
            View Full Dashboard →
          </Button>
        </CardContent>
      </Card>

      {/* Quick Actions */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card className="hover:shadow-lg transition-shadow cursor-pointer" onClick={() => navigate('/admin')}>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Users className="h-5 w-5 text-primary" />
              Manage Clients
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              View and manage client organizations and their settings
            </p>
          </CardContent>
        </Card>

        <Card className="hover:shadow-lg transition-shadow cursor-pointer">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-primary" />
              View Reports
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Access detailed analytics and performance reports
            </p>
          </CardContent>
        </Card>

        <Card className="hover:shadow-lg transition-shadow cursor-pointer">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Activity className="h-5 w-5 text-primary" />
              Monitor Campaigns
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Track active campaigns and their real-time metrics
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Charts Section */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Revenue Trends Chart */}
        <Card>
          <CardHeader>
            <CardTitle>Revenue & Spend Trends</CardTitle>
            <CardDescription>
              {dateRangePreset === 'custom' 
                ? `${format(customDateRange.from, 'MMM dd, yyyy')} - ${format(customDateRange.to, 'MMM dd, yyyy')}`
                : `Last ${dateRangePreset} days performance`
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#667eea" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#667eea" stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorSpend" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#f093fb" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#f093fb" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis 
                  dataKey="date" 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                />
                <YAxis 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                  tickFormatter={(value) => `$${(value / 1000).toFixed(0)}k`}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'hsl(var(--card))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                  formatter={(value: any) => `$${Number(value).toLocaleString()}`}
                />
                <Legend />
                <Area 
                  type="monotone" 
                  dataKey="revenue" 
                  stroke="#667eea" 
                  fillOpacity={1} 
                  fill="url(#colorRevenue)"
                  name="Revenue"
                />
                <Area 
                  type="monotone" 
                  dataKey="spend" 
                  stroke="#f093fb" 
                  fillOpacity={1} 
                  fill="url(#colorSpend)"
                  name="Spend"
                />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* ROI Over Time Chart */}
        <Card>
          <CardHeader>
            <CardTitle>ROI Trend</CardTitle>
            <CardDescription>
              {dateRangePreset === 'custom' 
                ? `ROI: ${format(customDateRange.from, 'MMM dd')} - ${format(customDateRange.to, 'MMM dd')}`
                : `Return on investment (${dateRangePreset} days)`
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <LineChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis 
                  dataKey="date" 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                />
                <YAxis 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                  tickFormatter={(value) => `${value}%`}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'hsl(var(--card))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                  formatter={(value: any) => `${Number(value).toFixed(1)}%`}
                />
                <Legend />
                <Line 
                  type="monotone" 
                  dataKey="roi" 
                  stroke="#43e97b" 
                  strokeWidth={3}
                  dot={{ fill: '#43e97b', r: 4 }}
                  name="ROI %"
                />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Campaign Performance Bar Chart */}
        <Card>
          <CardHeader>
            <CardTitle>Top Campaigns</CardTitle>
            <CardDescription>
              {dateRangePreset === 'custom' 
                ? `Performance in selected period`
                : `Top performers (${dateRangePreset} days)`
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={campaignData}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis 
                  dataKey="name" 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                  angle={-45}
                  textAnchor="end"
                  height={80}
                />
                <YAxis 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                  tickFormatter={(value) => `$${(value / 1000).toFixed(0)}k`}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'hsl(var(--card))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                  formatter={(value: any) => `$${Number(value).toLocaleString()}`}
                />
                <Legend />
                <Bar dataKey="revenue" fill="#667eea" name="Revenue" radius={[8, 8, 0, 0]} />
                <Bar dataKey="spend" fill="#764ba2" name="Spend" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Donations Trend Chart */}
        <Card>
          <CardHeader>
            <CardTitle>Donations Trend</CardTitle>
            <CardDescription>
              {dateRangePreset === 'custom' 
                ? `Donations: ${format(customDateRange.from, 'MMM dd')} - ${format(customDateRange.to, 'MMM dd')}`
                : `Number of donations (${dateRangePreset} days)`
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="colorDonations" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#4facfe" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#4facfe" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis 
                  dataKey="date" 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                />
                <YAxis 
                  className="text-xs"
                  tick={{ fill: 'hsl(var(--muted-foreground))' }}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: 'hsl(var(--card))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px'
                  }}
                  formatter={(value: any) => `${Number(value).toLocaleString()} donations`}
                />
                <Legend />
                <Area 
                  type="monotone" 
                  dataKey="donations" 
                  stroke="#4facfe" 
                  fillOpacity={1} 
                  fill="url(#colorDonations)"
                  name="Donations"
                />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Financial Overview */}
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Spending Overview</CardTitle>
            <CardDescription>Total advertising and SMS costs</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Total Spend</span>
                <span className="text-2xl font-bold">{formatCurrency(stats.totalSpend)}</span>
              </div>
              <div className="text-xs text-muted-foreground">
                Combined advertising and SMS campaign costs across all clients
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Performance Metrics</CardTitle>
            <CardDescription>Key performance indicators</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">Profit</span>
                <span className="text-2xl font-bold text-green-600">
                  {formatCurrency(stats.totalRevenue - stats.totalSpend)}
                </span>
              </div>
              <div className="text-xs text-muted-foreground">
                Net revenue after all campaign costs
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
