import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { format, subDays } from "date-fns";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useIsMobile } from "@/hooks/use-mobile";
import {
  TrendingUp,
  Users,
  DollarSign,
  BarChart3,
  Building2,
  Activity,
  ArrowUpRight,
  ArrowDownRight,
  Plus,
  LayoutDashboard,
  Target,
  Sparkles
} from "lucide-react";
import { logger } from "@/lib/logger";
import { DateRangeSelector } from "@/components/dashboard/DateRangeSelector";
import { EChartsLineChart, EChartsBarChart } from "@/components/charts/echarts";

interface DashboardStats {
  totalClients: number;
  activeClients: number;
  totalRevenue: number;
  totalSpend: number;
  avgROI: number;
  totalDonations: number;
  revenueChange: number;
  clientChange: number;
}

interface ChartDataPoint {
  date: string;
  revenue: number;
  spend: number;
  roi: number;
  donations: number;
}

interface CampaignPerformance {
  name: string;
  revenue: number;
  spend: number;
  roi: number;
}


export function DashboardHome() {
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [stats, setStats] = useState<DashboardStats>({
    totalClients: 0,
    activeClients: 0,
    totalRevenue: 0,
    totalSpend: 0,
    avgROI: 0,
    totalDonations: 0,
    revenueChange: 0,
    clientChange: 0,
  });
  const [chartData, setChartData] = useState<ChartDataPoint[]>([]);
  const [campaignData, setCampaignData] = useState<CampaignPerformance[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [startDate, setStartDate] = useState(format(subDays(new Date(), 30), 'yyyy-MM-dd'));
  const [endDate, setEndDate] = useState(format(new Date(), 'yyyy-MM-dd'));

  useEffect(() => {
    fetchDashboardStats();
  }, []);

  useEffect(() => {
    fetchChartData();
    fetchCampaignPerformance();
  }, [startDate, endDate]);

  const handleDateChange = (start: string, end: string) => {
    setStartDate(start);
    setEndDate(end);
  };

  const fetchDashboardStats = async () => {
    try {
      // Using any to bypass type issues with autogenerated types
      const orgsQuery = (supabase as any).from('client_organizations').select('id, is_active');
      const metricsQuery = (supabase as any).from('daily_aggregated_metrics').select('total_funds_raised, total_ad_spend, total_sms_cost, roi_percentage, total_donations');
      
      const [orgsResult, metricsResult] = await Promise.all([orgsQuery, metricsQuery]);
      
      const organizations = orgsResult.data || [];
      const metrics = metricsResult.data || [];

      // Calculate totals
      const totalRevenue = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_funds_raised) || 0), 0);
      const totalAdSpend = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_ad_spend) || 0), 0);
      const totalSmsSpend = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_sms_cost) || 0), 0);
      const totalSpend = totalAdSpend + totalSmsSpend;
      const totalDonations = metrics.reduce((sum: number, m: any) => sum + (Number(m.total_donations) || 0), 0);
      const avgROI = totalSpend > 0 ? ((totalRevenue - totalSpend) / totalSpend) * 100 : 0;

      setStats({
        totalClients: organizations.length,
        activeClients: organizations.filter((o: any) => o.is_active).length,
        totalRevenue,
        totalSpend,
        avgROI,
        totalDonations,
        revenueChange: 12.5,
        clientChange: 8.2,
      });
    } catch (error) {
      logger.error('Failed to fetch dashboard stats', error);
    } finally {
      setIsLoading(false);
    }
  };


  const fetchChartData = async () => {
    try {

      const { data: metrics } = await (supabase as any)
        .from('daily_aggregated_metrics')
        .select('date, total_funds_raised, total_ad_spend, total_sms_cost, roi_percentage, total_donations')
        .gte('date', startDate)
        .lte('date', endDate)
        .order('date', { ascending: true });

      if (metrics) {
        const formattedData: ChartDataPoint[] = metrics.map((m: any) => ({
          date: new Date(m.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
          revenue: Number(m.total_funds_raised) || 0,
          spend: Number(m.total_ad_spend) + Number(m.total_sms_cost) || 0,
          roi: Number(m.roi_percentage) || 0,
          donations: Number(m.total_donations) || 0,
        }));
        setChartData(formattedData);
      }
    } catch (error) {
      logger.error('Failed to fetch chart data', error);
    }
  };

  const fetchCampaignPerformance = async () => {
    try {

      // Fetch top campaigns by revenue
      const { data: campaigns } = await (supabase as any)
        .from('meta_campaigns')
        .select('campaign_name, campaign_id')
        .eq('status', 'ACTIVE')
        .limit(5);

      if (campaigns) {
        const performanceData: CampaignPerformance[] = await Promise.all(
          campaigns.map(async (campaign: any) => {
            const { data: metrics } = await (supabase as any)
              .from('meta_ad_metrics')
              .select('spend, conversions, conversion_value')
              .eq('campaign_id', campaign.campaign_id)
              .gte('date', startDate)
              .lte('date', endDate);

            const totalSpend = metrics?.reduce((sum: number, m: any) => sum + Number(m.spend || 0), 0) || 0;
            const totalRevenue = metrics?.reduce((sum: number, m: any) => sum + Number(m.conversion_value || 0), 0) || 0;
            const roi = totalSpend > 0 ? ((totalRevenue - totalSpend) / totalSpend) * 100 : 0;

            return {
              name: campaign.campaign_name || 'Unknown Campaign',
              revenue: totalRevenue,
              spend: totalSpend,
              roi: roi,
            };
          })
        );

        setCampaignData(performanceData.sort((a, b) => b.revenue - a.revenue));
      }
    } catch (error) {
      logger.error('Failed to fetch campaign performance', error);
    }
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const formatNumber = (value: number) => {
    return new Intl.NumberFormat('en-US').format(value);
  };


  if (isLoading) {
    return (
      <div className="space-y-6 portal-animate-fade-in">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="portal-card p-6 space-y-3" style={{ animationDelay: `${i * 100}ms` }}>
              <div className="portal-skeleton h-8 w-8 rounded-lg" />
              <div className="portal-skeleton h-4 w-24" />
              <div className="portal-skeleton h-8 w-32" />
            </div>
          ))}
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="portal-card p-6">
            <div className="portal-skeleton h-64 rounded" />
          </div>
          <div className="portal-card p-6">
            <div className="portal-skeleton h-64 rounded" />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header Section - Matches DailyBriefing Style */}
      <div className="space-y-4">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-950">
            <LayoutDashboard className="h-6 w-6 sm:h-7 sm:w-7 text-blue-600 dark:text-blue-400" />
          </div>
          <div className="flex-1 min-w-0">
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight">
              Dashboard Overview
            </h1>
            <p className="text-sm sm:text-base text-muted-foreground">
              Monitor performance and key metrics across all organizations
            </p>
          </div>
          {/* Demo Button - Desktop Only */}
          {!isMobile && (
            <Button
              onClick={() => navigate('/admin/client-view/a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d')}
              variant="secondary"
              size="sm"
              className="shrink-0"
            >
              <Sparkles className="h-4 w-4 mr-2" />
              View Demo
            </Button>
          )}
        </div>

        {/* Date Range Selector */}
        <DateRangeSelector
          startDate={startDate}
          endDate={endDate}
          onDateChange={handleDateChange}
        />
      </div>

      {/* Key Metrics Grid - Enhanced with Portal Styling */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total Revenue - Green */}
        <Card variant="elevated" className="portal-card portal-animate-fade-in hover:scale-[1.02] transition-transform duration-300" style={{ animationDelay: '0ms' }}>
          <CardContent className="p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="p-2 rounded-lg bg-green-100 dark:bg-green-950 transition-all duration-300">
                <DollarSign className="h-5 w-5 text-green-600 dark:text-green-400" />
              </div>
              {stats.revenueChange > 0 ? (
                <div className="flex items-center text-xs font-medium text-green-600 dark:text-green-400 portal-animate-scale-in">
                  <ArrowUpRight className="h-3 w-3 mr-1" />
                  +{stats.revenueChange}%
                </div>
              ) : (
                <div className="flex items-center text-xs font-medium text-red-600 dark:text-red-400 portal-animate-scale-in">
                  <ArrowDownRight className="h-3 w-3 mr-1" />
                  {stats.revenueChange}%
                </div>
              )}
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium portal-text-secondary">Total Revenue</p>
              <div className="text-3xl font-bold text-green-600 dark:text-green-400 tabular-nums">
                {formatCurrency(stats.totalRevenue)}
              </div>
              <p className="text-xs portal-text-secondary">from last month</p>
            </div>
          </CardContent>
        </Card>

        {/* Active Clients - Blue */}
        <Card variant="elevated" className="portal-card portal-animate-fade-in hover:scale-[1.02] transition-transform duration-300" style={{ animationDelay: '50ms' }}>
          <CardContent className="p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-950 transition-all duration-300">
                <Building2 className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              </div>
              {stats.clientChange > 0 && (
                <div className="flex items-center text-xs font-medium text-green-600 dark:text-green-400 portal-animate-scale-in">
                  <ArrowUpRight className="h-3 w-3 mr-1" />
                  +{stats.clientChange}%
                </div>
              )}
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium portal-text-secondary">Active Clients</p>
              <div className="text-3xl font-bold text-blue-600 dark:text-blue-400 tabular-nums">
                {stats.activeClients}
              </div>
              <p className="text-xs portal-text-secondary">of {stats.totalClients} total</p>
            </div>
          </CardContent>
        </Card>

        {/* Average ROI - Purple */}
        <Card variant="elevated" className="portal-card portal-animate-fade-in hover:scale-[1.02] transition-transform duration-300" style={{ animationDelay: '100ms' }}>
          <CardContent className="p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-950 transition-all duration-300">
                <TrendingUp className="h-5 w-5 text-purple-600 dark:text-purple-400" />
              </div>
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium portal-text-secondary">Average ROI</p>
              <div className="text-3xl font-bold text-purple-600 dark:text-purple-400 tabular-nums">
                {stats.avgROI.toFixed(1)}%
              </div>
              <p className="text-xs portal-text-secondary">Return on investment</p>
            </div>
          </CardContent>
        </Card>

        {/* Total Donations - Orange */}
        <Card variant="elevated" className="portal-card portal-animate-fade-in hover:scale-[1.02] transition-transform duration-300" style={{ animationDelay: '150ms' }}>
          <CardContent className="p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="p-2 rounded-lg bg-orange-100 dark:bg-orange-950 transition-all duration-300">
                <Users className="h-5 w-5 text-orange-600 dark:text-orange-400" />
              </div>
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium portal-text-secondary">Total Donations</p>
              <div className="text-3xl font-bold text-orange-600 dark:text-orange-400 tabular-nums">
                {formatNumber(stats.totalDonations)}
              </div>
              <p className="text-xs portal-text-secondary">Across all campaigns</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Demo Organization Card - Enhanced */}
      <Card variant="gradient" className="portal-card portal-animate-fade-in bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-950/20 dark:to-blue-950/20 border-purple-200 dark:border-purple-800">
        <CardHeader className="pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-950">
              <Sparkles className="h-5 w-5 text-purple-600 dark:text-purple-400" />
            </div>
            <div>
              <CardTitle className="text-xl portal-text-primary">Demo Organization</CardTitle>
              <CardDescription className="text-sm portal-text-secondary">
                Progressive Victory Fund • Sample Data
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-4 portal-bg-elevated rounded-lg border portal-border space-y-1 hover:scale-[1.02] transition-transform duration-300">
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-green-600 dark:text-green-400" />
                <div className="text-xs font-medium portal-text-secondary">Funds Raised</div>
              </div>
              <div className="text-2xl font-bold text-green-600 dark:text-green-400 tabular-nums">$245,750</div>
            </div>
            <div className="p-4 portal-bg-elevated rounded-lg border portal-border space-y-1 hover:scale-[1.02] transition-transform duration-300">
              <div className="flex items-center gap-2">
                <Target className="h-4 w-4 text-blue-600 dark:text-blue-400" />
                <div className="text-xs font-medium portal-text-secondary">Ad Spend</div>
              </div>
              <div className="text-2xl font-bold text-blue-600 dark:text-blue-400 tabular-nums">$18,500</div>
            </div>
            <div className="p-4 portal-bg-elevated rounded-lg border portal-border space-y-1 hover:scale-[1.02] transition-transform duration-300">
              <div className="flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-purple-600 dark:text-purple-400" />
                <div className="text-xs font-medium portal-text-secondary">ROI</div>
              </div>
              <div className="text-2xl font-bold text-purple-600 dark:text-purple-400 tabular-nums">1,228%</div>
            </div>
          </div>
          <Button
            onClick={() => navigate('/admin/client-view/a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d')}
            className="w-full min-h-[44px] hover:scale-[1.02] transition-all duration-300"
            size="lg"
          >
            View Full Dashboard →
          </Button>
        </CardContent>
      </Card>

      {/* Quick Actions - Redesigned */}
      <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
        <Card variant="elevated" className="cursor-pointer hover:border-blue-200 dark:hover:border-blue-800" onClick={() => navigate('/admin')}>
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-950">
                <Building2 className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              </div>
              <CardTitle className="text-lg">Manage Clients</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              View and manage client organizations and their settings
            </p>
          </CardContent>
        </Card>

        <Card variant="elevated" className="cursor-pointer hover:border-purple-200 dark:hover:border-purple-800">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-950">
                <BarChart3 className="h-5 w-5 text-purple-600 dark:text-purple-400" />
              </div>
              <CardTitle className="text-lg">View Reports</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Access detailed analytics and performance reports
            </p>
          </CardContent>
        </Card>

        <Card variant="elevated" className="cursor-pointer hover:border-orange-200 dark:hover:border-orange-800">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-orange-100 dark:bg-orange-950">
                <Activity className="h-5 w-5 text-orange-600 dark:text-orange-400" />
              </div>
              <CardTitle className="text-lg">Monitor Campaigns</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Track active campaigns and their real-time metrics
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Charts Section - Redesigned */}
      <div className="grid gap-6 grid-cols-1 md:grid-cols-2">
        {/* Revenue Trends Chart */}
        <Card variant="smooth" className="animate-slide-in-left">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-green-100 dark:bg-green-950">
                <DollarSign className="h-4 w-4 text-green-600 dark:text-green-400" />
              </div>
              <CardTitle className="text-lg">Revenue & Spend Trends</CardTitle>
            </div>
            <CardDescription className="text-sm">
              {format(new Date(startDate), 'MMM dd, yyyy')} - {format(new Date(endDate), 'MMM dd, yyyy')}
            </CardDescription>
          </CardHeader>
          <CardContent className="pb-4">
            <EChartsLineChart
              data={chartData}
              series={[
                { dataKey: 'revenue', name: 'Revenue', color: '#667eea', areaStyle: { opacity: 0.3 } },
                { dataKey: 'spend', name: 'Spend', color: '#f093fb', areaStyle: { opacity: 0.3 } },
              ]}
              xAxisKey="date"
              valueType="currency"
              height={isMobile ? 250 : 300}
              showLegend
            />
          </CardContent>
        </Card>

        {/* ROI Over Time Chart */}
        <Card variant="smooth" className="animate-slide-in-right">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-950">
                <TrendingUp className="h-4 w-4 text-purple-600 dark:text-purple-400" />
              </div>
              <CardTitle className="text-lg">ROI Trend</CardTitle>
            </div>
            <CardDescription className="text-sm">
              Return on investment: {format(new Date(startDate), 'MMM dd')} - {format(new Date(endDate), 'MMM dd')}
            </CardDescription>
          </CardHeader>
          <CardContent className="pb-4">
            <EChartsLineChart
              data={chartData}
              series={[
                { dataKey: 'roi', name: 'ROI %', color: '#43e97b' },
              ]}
              xAxisKey="date"
              valueType="percent"
              height={isMobile ? 250 : 300}
              showLegend
            />
          </CardContent>
        </Card>

        {/* Campaign Performance Bar Chart */}
        <Card variant="smooth" className="animate-fade-in">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-950">
                <BarChart3 className="h-4 w-4 text-blue-600 dark:text-blue-400" />
              </div>
              <CardTitle className="text-lg">Top Campaigns</CardTitle>
            </div>
            <CardDescription className="text-sm">
              Top performing campaigns in selected period
            </CardDescription>
          </CardHeader>
          <CardContent className="pb-4">
            <EChartsBarChart
              data={campaignData as unknown as Record<string, unknown>[]}
              series={[
                { dataKey: 'revenue', name: 'Revenue', color: '#667eea' },
                { dataKey: 'spend', name: 'Spend', color: '#764ba2' },
              ]}
              xAxisKey="name"
              valueType="currency"
              height={isMobile ? 250 : 300}
              showLegend
              xAxisLabelRotate={45}
            />
          </CardContent>
        </Card>

        {/* Donations Trend Chart */}
        <Card variant="smooth" className="animate-fade-in">
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-orange-100 dark:bg-orange-950">
                <Users className="h-4 w-4 text-orange-600 dark:text-orange-400" />
              </div>
              <CardTitle className="text-lg">Donations Trend</CardTitle>
            </div>
            <CardDescription className="text-sm">
              Donations: {format(new Date(startDate), 'MMM dd')} - {format(new Date(endDate), 'MMM dd')}
            </CardDescription>
          </CardHeader>
          <CardContent className="pb-4">
            <EChartsLineChart
              data={chartData}
              series={[
                { dataKey: 'donations', name: 'Donations', color: '#4facfe', areaStyle: { opacity: 0.3 } },
              ]}
              xAxisKey="date"
              valueType="number"
              height={isMobile ? 250 : 300}
              showLegend
            />
          </CardContent>
        </Card>
      </div>

      {/* Financial Overview - Redesigned */}
      <div className="grid gap-6 grid-cols-1 md:grid-cols-2">
        <Card>
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-red-100 dark:bg-red-950">
                <Target className="h-4 w-4 text-red-600 dark:text-red-400" />
              </div>
              <CardTitle className="text-lg">Spending Overview</CardTitle>
            </div>
            <CardDescription className="text-sm">Total advertising and SMS costs</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-muted-foreground">Total Spend</span>
                <span className="text-3xl font-bold text-red-600 dark:text-red-400">{formatCurrency(stats.totalSpend)}</span>
              </div>
              <p className="text-xs text-muted-foreground">
                Combined advertising and SMS campaign costs across all clients
              </p>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-4">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 rounded-lg bg-green-100 dark:bg-green-950">
                <TrendingUp className="h-4 w-4 text-green-600 dark:text-green-400" />
              </div>
              <CardTitle className="text-lg">Performance Metrics</CardTitle>
            </div>
            <CardDescription className="text-sm">Key performance indicators</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-muted-foreground">Net Profit</span>
                <span className="text-3xl font-bold text-green-600 dark:text-green-400">
                  {formatCurrency(stats.totalRevenue - stats.totalSpend)}
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Net revenue after all campaign costs
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
