/**
 * RefcodeGenerator - Auto-generates refcodes from video analysis
 *
 * Features:
 * - Auto-generates refcode on mount if value is empty
 * - Uses video analysis topic/issue for meaningful refcodes
 * - Allows manual editing with toggle
 * - Regenerate button to create new code
 */

import { useEffect, useState, useCallback } from 'react';
import { cn } from '@/lib/utils';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RefreshCw, Pencil, Check } from 'lucide-react';
import type { TranscriptAnalysis } from '@/types/ad-copy-studio';

// =============================================================================
// Types
// =============================================================================

export interface RefcodeGeneratorProps {
  videoAnalysis?: TranscriptAnalysis | null;
  value: string;
  onChange: (refcode: string, autoGenerated: boolean) => void;
  disabled?: boolean;
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Slugify a string for use in refcodes
 */
function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 20);
}

/**
 * Generate a short random string
 */
function generateShortId(): string {
  return Math.random().toString(36).substring(2, 6);
}

/**
 * Generate a date string for refcodes (MMDD format)
 */
function getDateString(): string {
  const date = new Date();
  return `${String(date.getMonth() + 1).padStart(2, '0')}${String(date.getDate()).padStart(2, '0')}`;
}

/**
 * Generate a refcode from video analysis
 */
function generateRefcode(analysis?: TranscriptAnalysis | null): string {
  const dateStr = getDateString();
  const shortId = generateShortId();

  if (analysis) {
    // Try to use topic or issue for meaningful refcode
    const topic = analysis.topic_primary || analysis.issue_primary;
    if (topic) {
      const slug = slugify(topic);
      if (slug) {
        return `${slug}-${dateStr}-${shortId}`;
      }
    }
  }

  // Fallback to generic campaign refcode
  return `campaign-${dateStr}-${shortId}`;
}

// =============================================================================
// Component
// =============================================================================

export function RefcodeGenerator({
  videoAnalysis,
  value,
  onChange,
  disabled = false,
}: RefcodeGeneratorProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(value);
  const [isAutoGenerated, setIsAutoGenerated] = useState(true);

  // Effect 1: Auto-generate on mount if no value
  useEffect(() => {
    if (!value) {
      const generated = generateRefcode(videoAnalysis);
      onChange(generated, true);
      setIsAutoGenerated(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Only run on mount
  }, []);

  // Effect 2: Regenerate when analysis becomes available and we're auto-generated
  useEffect(() => {
    if (videoAnalysis && isAutoGenerated && value) {
      const generated = generateRefcode(videoAnalysis);
      onChange(generated, true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Only react to videoAnalysis changes
  }, [videoAnalysis]);

  // Sync edit value with prop value
  useEffect(() => {
    if (!isEditing) {
      setEditValue(value);
    }
  }, [value, isEditing]);

  // =========================================================================
  // Handlers
  // =========================================================================

  const handleRegenerate = useCallback(() => {
    const generated = generateRefcode(videoAnalysis);
    onChange(generated, true);
    setIsAutoGenerated(true);
    setEditValue(generated);
    setIsEditing(false);
  }, [videoAnalysis, onChange]);

  const handleStartEdit = useCallback(() => {
    setEditValue(value);
    setIsEditing(true);
  }, [value]);

  const handleCancelEdit = useCallback(() => {
    setEditValue(value);
    setIsEditing(false);
  }, [value]);

  const handleSaveEdit = useCallback(() => {
    if (editValue.trim()) {
      onChange(editValue.trim(), false);
      setIsAutoGenerated(false);
      setIsEditing(false);
    }
  }, [editValue, onChange]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        handleSaveEdit();
      } else if (e.key === 'Escape') {
        handleCancelEdit();
      }
    },
    [handleSaveEdit, handleCancelEdit]
  );

  // =========================================================================
  // Render
  // =========================================================================

  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <Label className="text-xs font-medium uppercase tracking-wider text-[#64748b]">
          Refcode
        </Label>
        <div className="flex items-center gap-2">
          {!isEditing && !disabled && (
            <button
              type="button"
              onClick={handleStartEdit}
              className="flex items-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 transition-colors"
            >
              <Pencil className="h-3.5 w-3.5" />
              Edit
            </button>
          )}
          <button
            type="button"
            onClick={handleRegenerate}
            disabled={disabled}
            className={cn(
              'flex items-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 transition-colors',
              disabled && 'opacity-50 cursor-not-allowed'
            )}
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Regenerate
          </button>
        </div>
      </div>

      {isEditing ? (
        <div className="flex gap-2">
          <Input
            type="text"
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Enter refcode"
            className="flex-1 bg-[#0a0f1a] border-blue-500/50 text-[#e2e8f0] placeholder:text-[#64748b] focus-visible:ring-blue-500"
            autoFocus
          />
          <button
            type="button"
            onClick={handleCancelEdit}
            className="rounded-md px-3 py-2 text-sm bg-[#141b2d] border border-[#1e2a45] text-[#e2e8f0] hover:bg-[#1e2a45] transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSaveEdit}
            disabled={!editValue.trim()}
            className={cn(
              'rounded-md px-3 py-2 text-sm bg-blue-600 text-white hover:bg-blue-500 transition-colors flex items-center gap-1.5',
              !editValue.trim() && 'opacity-50 cursor-not-allowed'
            )}
          >
            <Check className="h-4 w-4" />
            Save
          </button>
        </div>
      ) : (
        <Input
          type="text"
          value={value}
          readOnly
          disabled={disabled}
          className="bg-[#0a0f1a] border-[#1e2a45] text-[#e2e8f0] placeholder:text-[#64748b]"
        />
      )}

      <p className="text-xs text-[#64748b]">
        {isAutoGenerated
          ? 'Auto-generated from video analysis. Edit if needed.'
          : 'Custom refcode entered.'}
      </p>
    </div>
  );
}

export default RefcodeGenerator;
